fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        default:
            locale: '%kernel.default_locale%' # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
        user:
            locale: '%kernel.default_locale%' # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                binds:
                    upload.presave:
                        - Plugin.AutoResize.onUpLoadPreSave
                plugins:
                    AutoResize: # global resize options, applies to root which don't have his own resize configuraion
                        enable: true
                        maxWidth: 1800
                        maxHeight: 1800
                        quality: 95 # JPEG image save quality
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 1800
                                maxHeight: 1800
                                quality: 95 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/x-shockwave-flash','audio/mpeg','audio/mp4','audio/ogg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 5M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                    detail:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/detailt
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 900
                                maxHeight: 400
                                quality: 70 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/x-shockwave-flash','audio/mpeg','audio/mp4','audio/ogg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                    info:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/info
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 255
                                maxHeight: 255
                                quality: 70 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/x-shockwave-flash','audio/mpeg','audio/mp4','audio/ogg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                    thumb:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/thumb
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 135
                                maxHeight: 135
                                quality: 70 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/x-shockwave-flash','audio/mpeg','audio/mp4','audio/ogg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                    icon:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/icon
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 18
                                maxHeight: 18
                                quality: 50 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/x-shockwave-flash','audio/mpeg','audio/mp4','audio/ogg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }

        admin:
            locale: '%kernel.default_locale%' # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                binds:
                    upload.presave:
                        - Plugin.AutoResize.onUpLoadPreSave
                plugins:
                    AutoResize: # global resize options, applies to root which don't have his own resize configuraion
                        enable: true
                        maxWidth: 1800
                        maxHeight: 1800
                        quality: 95 # JPEG image save quality
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 1800
                                maxHeight: 1800
                                quality: 95 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/x-shockwave-flash','audio/mpeg','audio/mp4','audio/ogg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                    detail:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/detailt
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 255
                                maxHeight: 255
                                quality: 70 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/x-shockwave-flash','audio/mpeg','audio/mp4','audio/ogg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                    info:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/info
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 255
                                maxHeight: 255
                                quality: 70 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/x-shockwave-flash','audio/mpeg','audio/mp4','audio/ogg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                    thumb:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/thumb
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 135
                                maxHeight: 135
                                quality: 70 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/x-shockwave-flash','audio/mpeg','audio/mp4','audio/ogg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                    icon:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/icon
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 18
                                maxHeight: 18
                                quality: 50 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg','application/x-shockwave-flash','audio/mpeg','audio/mp4','audio/ogg','application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }

# banner the definition for the
# advertising banner function for the user
#
        banner:
            locale: '%kernel.default_locale%' # defaults to current request locale
            editor: form # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                binds:
                    upload.presave:
                        - Plugin.AutoResize.onUpLoadPreSave
                    plugins:
                        AutoResize: # global resize options, applies to root which don't have his own resize configuraion
                            enable: true
                            maxWidth: 255
                            maxHeight: 255
                            quality: 80 # JPEG image save quality
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/banner
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                        plugins:
                            AutoResize: # resize configuraion
                                enable: true
                                maxWidth: 355
                                maxHeight: 255
                                quality: 80 # JPEG image save quality