twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # make the OpenWeatherService vars global public
        openweather: '@App\Service\OpenWeatherService'

    form_themes: ['bootstrap_4_layout.html.twig']

    paths:
        '%kernel.project_dir%/vendor/helios-ag/fm-elfinder-bundle/src/Resources/views': FMElfinderBundle