version: "3"

services:
  webserver:
    build:
      context: ./docker/bin/webserver
    container_name: 'altmuehlsee-apache'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-.}:/var/www/html
      - ${PHP_INI-./docker/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./docker/config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./docker/logs/apache2}:/var/log/apache2
    environment:
      - _SYSTEM_DEBUG=true
  mysql:
    build: ./docker/bin/mysql
    container_name: 'altmuehlsee-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./docker/data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./docker/logs/mysql}:/var/log/mysql
      - ${MYSQL_CONFIG-./docker/config/mysql/mycustom.cnf}:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sym_muehlsee
      MYSQL_USER: sym_muehlsee_user
      MYSQL_PASSWORD: sym_muehlsee_pw
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'altmuehlsee-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions