version: "3"

services:
  webserver:
    build:
      context: ./docker/bin/webserver
    container_name: 'apache-altmuehlsee'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-.}:/var/www/html:cached
      - ${PHP_INI-./docker/config/php/php.ini}:/usr/local/etc/php/php.ini:cached
      - ${VHOSTS_DIR-./docker/config/vhosts}:/etc/apache2/sites-enabled:cached
      - ${LOG_DIR-./docker/logs/apache2}:/var/log/apache2:cached
  mysql:
    build: ./docker/bin/mysql
    container_name: 'mysql-altmuehlsee'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./docker/data/mysql}:/var/lib/mysql:cached
      - ${MYSQL_LOG_DIR-./docker/logs/mysql}:/var/log/mysql:cached
      - ${MYSQL_CONFIG-./docker/config/mysql/mycustom.cnf}:/etc/mysql/conf.d/custom.cnf:cached
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sym_muehlsee
      MYSQL_USER: sym_muehlsee_user
      MYSQL_PASSWORD: sym_muehlsee_pw
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin-altmuehlsee'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions